[package]
name = "operating_systems"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.12"
itertools = "0.11.0"
num-bigint = "0.4.3"
num-integer = "0.1.45"
